const button9 = document.getElementById("9")
const button8 = document.getElementById("8")
const button7 = document.getElementById("7")
const button6 = document.getElementById("6")
const button5 = document.getElementById("5")
const button4 = document.getElementById("4")
const button3 = document.getElementById("3")
const button2 = document.getElementById("2")
const button1 = document.getElementById("1")
const button0 = document.getElementById("0")
const buttonDel = document.getElementById("DEL")
const buttonPlus = document.getElementById("+")
const buttonMoins = document.getElementById("-")
const buttonFois = document.getElementById("X")
const buttonSlash = document.getElementById("/")
const buttonPoint = document.getElementById(".")
const buttonReset = document.getElementById("RESET")
const buttonEgal = document.getElementById("=")


